name: 'Terraform'

on:
  push:
    branches:
    - "main"

jobs:  
  development_plan:
    uses: ./.github/workflows/terraform-plan.yml                
    with:
        environment: "development"
        TerraformBackendStorageAccount: "strterraformweu"
        TerraformBackendResourceGroup: "rg-terraform"
        TerraformBackendStorageContainer: "state"
        TerraformBackendStorageKey: "terraform.tfstate"
    secrets: inherit
  development_apply:
    uses: ./.github/workflows/terraform-apply.yml                
    needs: development_plan
    with:
        environment: "development"
        TerraformBackendStorageAccount: "strterraformweu"
        TerraformBackendResourceGroup: "rg-terraform"
        TerraformBackendStorageContainer: "state"
        TerraformBackendStorageKey: "terraform.tfstate"
        plan: ${{ needs.development_plan.outputs.plan }}
        artifact: ${{ needs.development_plan.outputs.artifact }}
    secrets: inherit