name: 'Terraform'

on:
  push:
    branches:
    - "main"

jobs:
  development_plan:
    uses: ./.github/workflows/terraform-plan.yml            
    with:
        environment: ${{ env.environment }}
    secrets: inherit