name: 'Terraform'

on:
  push:
    branches:
    - "main"

jobs:  
  development_plan:
    uses: ./.github/workflows/terraform-plan.yml                
    with:
        environment: "development"
        TerraformBackendStorageAccount: "strterraformweu"
        TerraformBackendResourceGroup: "rg-terraform"
        TerraformBackendStorageContainer: "state"
        TerraformBackendStorageKey: "terraform.tfstate"
    secrets: inherit