name: 'Terraform'

on:
  push:
    branches:
    - "main"

jobs:
  development_plan:
    runs-on: ubuntu-latest
    name: "Development: plan"
    steps:
      - uses: actions/terraform-plan
        with:
          environment: "development"