name: 'Terraform'

on:
  push:
    branches:
    - "main"

jobs:  
  development_plan:
    uses: ./.github/workflows/terraform-plan.yml                
    with:
        environment: "development"
        TerraformBackendStorageAccount: "strterraformweu"
        TerraformBackendResourceGroup: "rg-terraform"
        TerraformBackendStorageContainer: "state"
        TerraformBackendStorageKey: "development.tfstate"
        code: "dev"
    secrets: inherit
  development_apply:
    uses: ./.github/workflows/terraform-apply.yml                
    needs: development_plan
    with:
        environment: "development"
        TerraformBackendStorageAccount: "strterraformweu"
        TerraformBackendResourceGroup: "rg-terraform"
        TerraformBackendStorageContainer: "state"
        TerraformBackendStorageKey: "development.tfstate"
        code: "dev"
        plan: ${{ needs.development_plan.outputs.plan }}
        artifact: ${{ needs.development_plan.outputs.artifact }}        
    secrets: inherit
  acceptance_plan:
    uses: ./.github/workflows/terraform-plan.yml                
    with:
        environment: "acceptance"
        TerraformBackendStorageAccount: "strterraformweu"
        TerraformBackendResourceGroup: "rg-terraform"
        TerraformBackendStorageContainer: "state"
        TerraformBackendStorageKey: "acceptance.tfstate"
        code: "acc"
    secrets: inherit
  acceptance_apply:
    uses: ./.github/workflows/terraform-apply.yml                
    needs: acceptance_plan
    with:
        environment: "acceptance"
        TerraformBackendStorageAccount: "strterraformweu"
        TerraformBackendResourceGroup: "rg-terraform"
        TerraformBackendStorageContainer: "state"
        TerraformBackendStorageKey: "acceptance.tfstate"
        code: "dev"
        plan: ${{ needs.acceptance_plan.outputs.plan }}
        artifact: ${{ needs.acceptance_plan.outputs.artifact }}        
    secrets: inherit
  production_plan:
    uses: ./.github/workflows/terraform-plan.yml                
    with:
        environment: "production"
        TerraformBackendStorageAccount: "strterraformweu"
        TerraformBackendResourceGroup: "rg-terraform"
        TerraformBackendStorageContainer: "state"
        TerraformBackendStorageKey: "production.tfstate"
        code: "prd"
    secrets: inherit
  production_apply:
    uses: ./.github/workflows/terraform-apply.yml                
    needs: production_plan
    with:
        environment: "production"
        TerraformBackendStorageAccount: "strterraformweu"
        TerraformBackendResourceGroup: "rg-terraform"
        TerraformBackendStorageContainer: "state"
        TerraformBackendStorageKey: "production.tfstate"
        code: "dev"
        plan: ${{ needs.production_plan.outputs.plan }}
        artifact: ${{ needs.production_plan.outputs.artifact }}        
    secrets: inherit
