name: 'Terraform'

on:
  push:
    branches:
    - "main"

jobs:
  development_plan:
    runs-on: ubuntu-latest
    name: "Development: plan"
    env:
      environment: "development"
    environment: "development"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/terraform-plan.yml@main
        with:
          environment: ${{ env.environment }}